# -*- coding: utf-8 -*-
"""ConfigfileEshita.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EwJf7rnTDilURnfz7my8PPQZ_6Fs3OUZ

# CS246 - Colab 3
## K-Means & PCA

### Setup

Let's set up Spark on your Colab environment.  Run the cell below!
"""

!pip install pyspark
!pip install -U -q PyDrive
!apt install openjdk-8-jdk-headless -qq
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

"""Now we import some of the libraries usually needed by our workload.




"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import pyspark
from pyspark.sql import *
from pyspark.sql.types import *
from pyspark.sql.functions import *
from pyspark import SparkContext, SparkConf

"""Let's initialize the Spark context."""

# create the session
conf = SparkConf().set("spark.ui.port", "4050")

# create the context
sc = pyspark.SparkContext(conf=conf)
spark = SparkSession.builder.getOrCreate()

"""### Data Preprocessing"""

arrayData = [
        ('James',['Java','Scala'],{'hair':'black','eye':'brown'}),
        ('Michael',['Spark','Java',None],{'hair':'brown','eye':None}),
        ('Robert',['CSharp',''],{'hair':'red','eye':''}),
        ('Washington',None,None),
        ('Jefferson',['1','2'],{}) ]

df = spark.createDataFrame(data=arrayData, schema = ['name','knownLanguages','properties'])
df2 = df.select(df.name,explode(df.properties))
df2 = df.select(df.name,explode_outer(df.properties))
df2 = df.select(df.name,posexplode(df.properties))
df2 = df.select(df.name,posexplode_outer(df.properties))
df2.show()

dict = {
    "name":"Eshita",
    "degree":"Btech"
}
newframe = spark.createDataFrame([tuple(dict.values())],list(dict.keys()))
newframe.show()

#myset= {"apple", "banana", "cherry"} sample set
#mylist= ["apple", "banana", "cherry"] sample list
#mydict= {key=value,key1=value1} key value pair
#mytuple=[('1',{key:value})] sample tuple

df = spark.createDataFrame([("Eshita","1",["beautiful","tall"]),("Eshani","3",None)],['name','marks','attributes'])
s = df.agg({"marks":"sum"}).collect() #sum,max,min,avg
print(s[0][0])

df.select("name",posexplode_outer(df.attributes)).show()  #explode,explode_outer,posexplode,posexplode_outer

simpleData = [("James","Sales","NY",90000,34,10000),
    ("Michael","Sales","NY",86000,56,20000),
    ("Robert","Sales","CA",81000,30,23000),
    ("Maria","Finance","CA",90000,24,23000),
    ("Raman","Finance","CA",99000,40,24000),
    ("Scott","Finance","NY",83000,36,19000),
    ("Jen","Finance","NY",79000,53,15000),
    ("Jeff","Marketing","CA",80000,25,18000),
    ("Kumar","Marketing","NY",91000,50,21000)
  ]

schema = ["employee_name","department","state","salary","age","bonus"]
df = spark.createDataFrame(data=simpleData, schema = schema)
#df.show()

# Write to CSV file
#df.write.mode("overwrite").csv("sample_data/check/partition.csv")
#%rm -rf "sample_data/check/"

df2 = df.repartition(numPartitions=3)
print(df2.rdd.getNumPartitions())

df2 = df.repartition(numPartitions=2)
print(df2.rdd.getNumPartitions())

df2 = df.repartition(numPartitions=2)
print(df2.rdd.getNumPartitions())
# Write DataFrame to CSV file
#df2.write.mode("overwrite").csv("/sample_data/partitions.csv")

df2 = df.repartition("state")
print(df2.rdd.getNumPartitions())

from pyspark.sql.types import StructField, StructType, DoubleType,StringType,LongType


citySchema = StructType([

        StructField("city", StringType()),

        StructField("country", StringType()),

        StructField("latitude", DoubleType()),

        StructField("longitude", DoubleType()),

        StructField("population", LongType())

            ])

# df = spark.read.format("csv").schema(citySchema).option("header", "true").option("delimiter", ',').option("mode","permissive").load("/content/sample_data/sample.txt")
# df.show()

df = spark.read.format("csv").schema(citySchema).option("header", "true").option("delimiter", ',').option("mode","dropmalformed").load("/content/sample_data/sample.txt")
df.show()

df = spark.read.format("csv").schema(citySchema).option("header", "true").option("delimiter", ',').option("mode","failfast").load("/content/sample_data/sample.txt")
df.show()

emp = [(1,"Smith",-1,"2018","10","M",3000), \
    (2,"Rose",1,"2010","20","M",4000), \
    (3,"Williams",1,"2010","10","M",1000), \
    (4,"Jones",2,"2005","10","F",2000), \
    (5,"Brown",2,"2010","40","",-1), \
      (6,"Brown",2,"2010","50","",-1) \
  ]
empColumns = ["emp_id","name","superior_emp_id","year_joined", \
       "emp_dept_id","gender","salary"]

empDF = spark.createDataFrame(data=emp, schema = empColumns)
empDF.printSchema()
empDF.show(truncate=False)

dept = [("Finance",10), \
    ("Marketing",20), \
    ("Sales",30), \
    ("IT",40) \
  ]
deptColumns = ["dept_name","dept_id"]
deptDF = spark.createDataFrame(data=dept, schema = deptColumns)
deptDF.printSchema()
deptDF.show(truncate=False)

empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"inner") \
     .show(truncate=False)

empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"outer") \
    .show(truncate=False)
empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"full") \
    .show(truncate=False)
empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"fullouter") \
    .show(truncate=False)

empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"left").show(truncate=False)
empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"leftouter").show(truncate=False)

empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"right") \
   .show(truncate=False)
empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"rightouter") \
   .show(truncate=False)

empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"leftsemi") \
   .show(truncate=False)

empDF.join(deptDF,empDF.emp_dept_id ==  deptDF.dept_id,"leftanti") \
   .show(truncate=False)